### ISSUE TITLE
Especificar o CDU006 - Login

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#10]
Especificar o CDU006 - Login com base no diagrama do modelo de dados e do Main de prova de conceito. Deve ser feita a descrição e os fluxos principal e secundário. Os diagramas de classe e sequência são opcionais neste momento.

Lembrar que além do login será necessário a definição de papeis para o uso das funcionalidades do sistema.

As tabelas referentes ao login não estão diretamente ligada ao modelo de dados, e sim, as necessidades de segurança.

**Comment by felipesilvabsi** [comment]
Estou com alguns problemas de configuração do projeto com o maven. Com as dependecias do pom.xml para o spring framework, spring security e jsf 2.1 pois o projeto não esta reconhecendo as bibliotecas

**Comment by tacianosilva** [comment]
Oi @felipesilvabsi não entendi bem a sua pergunta, mas vou colocar algumas dependências aqui para implementar o CDU005 - Manter Curso. Se puder detalhar o problema!
