### ISSUE TITLE
Git não faz Pull da pasta DOCS do Projeto

### ISSUE THREAD

**Issue by aragonense** [tacianosilva/sigest#12]
Hoje pela manha tentei fazer um Pull do Projeto após a inclusao doas arquivos de Scirpt do BD, mas diz que não há atualizações para o projeto

**Comment by tacianosilva** [comment]
Você está fazendo pull de qual branch? Acho que o branch que tem a pasta docs é o branch modelo.

**Comment by tacianosilva** [comment]
E aí @aragonense resolveu?

**Comment by aragonense** [comment]
Resolvi com ajuda de @fladson
