### ISSUE TITLE
Incosistencia do Banco de Dados?

### ISSUE THREAD

**Issue by aragonense** [tacianosilva/sigest#22]
Por que dataCadastro é varchar e o restante é do tipo Date? Alguma especificação que não nos foi repassada?

  data_inicio date,
  data_fim date,
  data_cadastro character varying

**Comment by tacianosilva** [comment]
Na classe do model Estágio os tipos dos atributos são todos do tipo Date. Contudo, na tabela Estágio existia a inconsistência que foi corrigida. Neste momento todos as colunas mencionadas são do tipo Date.
