### ISSUE TITLE
Criar Script SQL do Modelo de Dados

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#4]
Criar script SQL do modelo de dados do projeto e acrescentar no diretório docs/scripts, arquivo com extensão ".sql".

**Comment by fladson** [comment]
Acredito que o seguinte commit 45fcab3f830b6014dd24cffc668d93d21183a7ca resolve a issue.
Favor analisar e fechar.

**Comment by tacianosilva** [comment]
Atividade completa!
