### ISSUE TITLE
Especificar o CDU001 - Estagiário

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#5]
Especificar o CDU001 - Estagiário com base no diagrama do modelo de dados e do Main de prova de conceito. Deve ser feita a descrição e os fluxos principal e secundário. Os diagramas de classe e sequência são opcionais neste momento.

**Comment by fladson** [comment]
Commit com a solução foi feito, favor ver e fechar a Issue.

**Comment by tacianosilva** [comment]
Ok, tarefa fechada! Como faz para fazer o link com o código?
