### ISSUE TITLE
Especificar o CDU002 - Estágio

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#6]
Especificar o CDU002 - Estágio com base no diagrama do modelo de dados e do Main de prova de conceito. Deve ser feita a descrição e os fluxos principal e secundário. Os diagramas de classe e sequência são opcionais neste momento.

**Comment by aragonense** [comment]
Commitado mas ainda faltam alguns esclarecimentos sobre a descrição do caso de uso.
