### ISSUE TITLE
Especificar o CDU003 - Empresa

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#7]
Especificar o CDU003 - Empresa com base no diagrama do modelo de dados e do Main de prova de conceito. Deve ser feita a descrição e os fluxos principal e secundário. Os diagramas de classe e sequência são opcionais neste momento.

**Comment by fladson** [comment]
Especificação feita por @alissongarcia no commit bb8460907fa6d1a48b29e41c18d55b088b87c927 
Fechando a issue.

**Comment by tacianosilva** [comment]
@fladson Porque o próprio @alissongarcia não fechou a tarefa?

**Comment by fladson** [comment]
@tacianosilva Talvez ele não esteja a par dessa funcionalidade e uma vez que todos do grupo podem fazer isso, desde que seja comprovado que a issue foi resolvida, tomei a liberdade. :smile:
