### ISSUE TITLE
Especificar o CDU004 - Professor

### ISSUE THREAD

**Issue by tacianosilva** [tacianosilva/sigest#8]
Especificar o CDU004 - Professor com base no diagrama do modelo de dados e do Main de prova de conceito. Deve ser feita a descrição e os fluxos principal e secundário. Os diagramas de classe e sequência são opcionais neste momento.

**Comment by fladson** [comment]
Espeecificação feita por @MerciaMaia no commit 3a62345f61b8a930d48a0284683307e54874fbb1
Fechando a issue.

**Comment by tacianosilva** [comment]
@fladson Porque o próprio @MerciaMaia não fechou a tarefa?

**Comment by fladson** [comment]
@tacianosilva todos do grupo podem fazer isso, desde que seja comprovado que a issue foi resolvida.
